# Generated by Django 4.0.2 on 2022-02-06 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TopTen', '0002_alter_top_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top',
            name='Time',
        ),
        migrations.AddField(
            model_name='top',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='top',
            name='Title',
            field=models.CharField(max_length=200),
        ),
    ]
