# Generated by Django 4.0.2 on 2022-02-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopTen', '0003_remove_top_time_top_created_date_alter_top_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top',
            old_name='Image',
            new_name='image',
        ),
    ]
