# Generated by Django 4.0.2 on 2022-02-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopTen', '0004_rename_image_top_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top',
            old_name='image',
            new_name='uploadedImage',
        ),
    ]
