# Generated by Django 4.0.2 on 2022-02-14 18:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('TopTen', '0010_alter_top_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='uploadedImage',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPG', keep_meta=True, quality=0, size=[300, 300], upload_to=''),
        ),
    ]
