# Generated by Django 4.0.2 on 2022-02-14 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TopTen', '0013_alter_top_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top',
            name='uploadedImage',
        ),
        migrations.AddField(
            model_name='top',
            name='images',
            field=models.ImageField(default=datetime.datetime(2022, 2, 14, 20, 6, 4, 651070, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
