# Generated by Django 4.0.2 on 2022-02-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopTen', '0014_remove_top_uploadedimage_top_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='Imdb_number',
            field=models.IntegerField(default=0),
        ),
    ]
